<a href="https://colab.research.google.com/github/howsam/pytorch-tutorial/blob/master/special_tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [3]:
zeros0d = torch.zeros(1)

print(zeros0d)

tensor([0.])


In [4]:
zeros1d = torch.zeros(5)

print(zeros1d)

tensor([0., 0., 0., 0., 0.])


In [5]:
zeros2d = torch.zeros(2, 3)

print(zeros2d)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
zeros5d = torch.zeros(2, 3, 8, 6, 5)

print(zeros5d.shape)

torch.Size([2, 3, 8, 6, 5])


In [0]:
ones1d = torch.ones(4)
print(ones1d)

ones2d = torch.ones(4, 8)
print(ones2d)

ones2d = torch.ones(1, 2, 1, dtype=torch.int16)
print(ones2d)

In [10]:
torch.eye(5)

torch.eye(5, 4)

torch.eye(4, 5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])

In [12]:
torch.full((5, 5))

TypeError: ignored