<a href="https://colab.research.google.com/github/howsam/pytorch-tutorial/blob/master/special_tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

# zeros

In [3]:
zeros0d = torch.zeros(1)
print(zeros0d)

tensor([0.])


In [4]:
zeros1d = torch.zeros(5)
print(zeros1d)

tensor([0., 0., 0., 0., 0.])


In [5]:
zeros2d = torch.zeros(2, 3)
print(zeros2d)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
zeros5d = torch.zeros(2, 3, 8, 6, 5)
print(zeros5d.shape)

torch.Size([2, 3, 8, 6, 5])


# ones

In [7]:
ones1d = torch.ones(4)
print(ones1d)

ones2d = torch.ones(4, 8)
print(ones2d)

ones2d = torch.ones(1, 2, 1, dtype=torch.int16)
print(ones2d)

tensor([1., 1., 1., 1.])
tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[[1],
         [1]]], dtype=torch.int16)


# eye

In [8]:
eye1d = torch.eye(5)
print(eye1d)

eye2d = torch.eye(5, 4)
print(eye2d)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])


# full

In [11]:
full1d = torch.full((5, 5), -8.5)
print(full1d)

tensor([[-8.5000, -8.5000, -8.5000, -8.5000, -8.5000],
        [-8.5000, -8.5000, -8.5000, -8.5000, -8.5000],
        [-8.5000, -8.5000, -8.5000, -8.5000, -8.5000],
        [-8.5000, -8.5000, -8.5000, -8.5000, -8.5000],
        [-8.5000, -8.5000, -8.5000, -8.5000, -8.5000]])


# arange

In [12]:
arange_tensor = torch.arange(0, 10, 1)
print(arange_tensor)

arange_tensor = torch.arange(10)
print(arange_tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [13]:
arange_tensor = torch.arange(1.5, 2.5, 0.1)
print(arange_tensor)

tensor([1.5000, 1.6000, 1.7000, 1.8000, 1.9000, 2.0000, 2.1000, 2.2000, 2.3000,
        2.4000])


# linspace

In [14]:
linspace_tensor = torch.linspace(0, 1, 100)
print(linspace_tensor)

tensor([0.0000, 0.0101, 0.0202, 0.0303, 0.0404, 0.0505, 0.0606, 0.0707, 0.0808,
        0.0909, 0.1010, 0.1111, 0.1212, 0.1313, 0.1414, 0.1515, 0.1616, 0.1717,
        0.1818, 0.1919, 0.2020, 0.2121, 0.2222, 0.2323, 0.2424, 0.2525, 0.2626,
        0.2727, 0.2828, 0.2929, 0.3030, 0.3131, 0.3232, 0.3333, 0.3434, 0.3535,
        0.3636, 0.3737, 0.3838, 0.3939, 0.4040, 0.4141, 0.4242, 0.4343, 0.4444,
        0.4545, 0.4646, 0.4747, 0.4848, 0.4949, 0.5051, 0.5152, 0.5253, 0.5354,
        0.5455, 0.5556, 0.5657, 0.5758, 0.5859, 0.5960, 0.6061, 0.6162, 0.6263,
        0.6364, 0.6465, 0.6566, 0.6667, 0.6768, 0.6869, 0.6970, 0.7071, 0.7172,
        0.7273, 0.7374, 0.7475, 0.7576, 0.7677, 0.7778, 0.7879, 0.7980, 0.8081,
        0.8182, 0.8283, 0.8384, 0.8485, 0.8586, 0.8687, 0.8788, 0.8889, 0.8990,
        0.9091, 0.9192, 0.9293, 0.9394, 0.9495, 0.9596, 0.9697, 0.9798, 0.9899,
        1.0000])


# empty

In [15]:
empty_tensor = torch.empty(2,2)
print(empty_tensor)

tensor([[1.7925e-35, 0.0000e+00],
        [3.3631e-44, 0.0000e+00]])
