<a href="https://colab.research.google.com/github/howsam/pytorch-tutorial/blob/master/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [9]:
tensor0d = torch.tensor(1)

print(tensor0d)

tensor(1)


In [15]:
tensor1d = torch.tensor([1, -1, 15, 1000])

print(tensor1d)

tensor([   1,   -1,   15, 1000])


In [11]:
tensor2d = torch.tensor([[-10,  11,   1.5],
                         [ 5.6, 88,  10.0],
                         [ 2.3, 36, -10.0],
                         [ 2.0, 12,   0.2]])

print(tensor2d)

tensor([[-10.0000,  11.0000,   1.5000],
        [  5.6000,  88.0000,  10.0000],
        [  2.3000,  36.0000, -10.0000],
        [  2.0000,  12.0000,   0.2000]])


In [13]:
tensor3d = torch.tensor([[[-10,   11,   1.50],
                         [ 5.6,   88,   10.0],
                         [ 2.3,   36,  -10.0],
                         [ 2.0,   12,    0.2]],
                         [[-1.0,  11,   1.50],
                          [ 0.6,  88,   1.00],
                          [ 0.3,  3.6, -10.0],
                          [ 2.1,  1.2,  4.20]]
                         ])

print(tensor3d)

tensor([[[-10.0000,  11.0000,   1.5000],
         [  5.6000,  88.0000,  10.0000],
         [  2.3000,  36.0000, -10.0000],
         [  2.0000,  12.0000,   0.2000]],

        [[ -1.0000,  11.0000,   1.5000],
         [  0.6000,  88.0000,   1.0000],
         [  0.3000,   3.6000, -10.0000],
         [  2.1000,   1.2000,   4.2000]]])


In [17]:
dims = tensor2d.shape

print(dims)

torch.Size([4, 3])


In [21]:
dims2 = tensor2d.size()

print(dims2)

torch.Size([4, 3])


In [19]:
dtype = tensor1d.dtype

print(dtype)

torch.int64
